INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (1, 'Camila MartÃ­nez', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (2, 'Juan GÃ³mez', 'BogotÃ¡', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (3, 'Valentina LÃ³pez', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (4, 'Ana PÃ©rez', 'Cali', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (5, 'Carlos MartÃ­nez', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (6, 'Isabella Vergara', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (7, 'Paula RodrÃ­guez', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (8, 'AndrÃ©s MartÃ­nez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (9, 'Valentina MartÃ­nez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (10, 'Fernando GÃ³mez', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (11, 'Carlos PÃ©rez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (12, 'MarÃ­a MartÃ­nez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (13, 'SofÃ­a PÃ©rez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (14, 'Camila Valencia', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (15, 'Carlos GarcÃ­a', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (16, 'Luis SÃ¡nchez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (17, 'Juan PÃ©rez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (18, 'MarÃ­a DÃ­az', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (19, 'Luis GarcÃ­a', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (20, 'Fernando Valencia', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (21, 'Alejandro DÃ­az', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (22, 'Gabriel PÃ©rez', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (23, 'Javier LÃ³pez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (24, 'Javier GÃ³mez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (25, 'Alejandro RodrÃ­guez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (26, 'Luis GarcÃ­a', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (27, 'Luis DÃ­az', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (28, 'Juan RodrÃ­guez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (29, 'Diana DÃ­az', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (30, 'Laura DÃ­az', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (31, 'MarÃ­a DÃ­az', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (32, 'Luis MartÃ­nez', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (33, 'Diana Vergara', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (34, 'Isabella MartÃ­nez', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (35, 'Paula RodrÃ­guez', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (36, 'AndrÃ©s Vergara', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (37, 'Javier LÃ³pez', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (38, 'Ana SÃ¡nchez', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (39, 'Fernando PÃ©rez', 'Cali', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (40, 'Carlos Vergara', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (41, 'MarÃ­a PÃ©rez', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (42, 'Juan DÃ­az', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (43, 'Valentina GÃ³mez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (44, 'Juan SÃ¡nchez', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (45, 'Fernando Valencia', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (46, 'Isabella LÃ³pez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (47, 'Laura PÃ©rez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (48, 'Alejandro SÃ¡nchez', 'BogotÃ¡', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (49, 'Valentina DÃ­az', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (50, 'Luis GarcÃ­a', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (51, 'Valentina SÃ¡nchez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (52, 'Ana Valencia', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (53, 'Carlos Valencia', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (54, 'Juan Vergara', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (55, 'Diana RodrÃ­guez', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (56, 'Laura GarcÃ­a', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (57, 'Carlos Valencia', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (58, 'AndrÃ©s Valencia', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (59, 'Juan PÃ©rez', 'Cali', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (60, 'Valentina DÃ­az', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (61, 'Camila Vergara', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (62, 'Camila SÃ¡nchez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (63, 'Valentina Valencia', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (64, 'Camila GÃ³mez', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (65, 'Diana Valencia', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (66, 'Paula RodrÃ­guez', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (67, 'Valentina RodrÃ­guez', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (68, 'MarÃ­a LÃ³pez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (69, 'Paula SÃ¡nchez', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (70, 'MarÃ­a RodrÃ­guez', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (71, 'MarÃ­a Vergara', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (72, 'Camila Vergara', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (73, 'Luis MartÃ­nez', 'Cali', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (74, 'Camila RodrÃ­guez', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (75, 'Ana SÃ¡nchez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (76, 'AndrÃ©s Valencia', 'BogotÃ¡', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (77, 'Diego DÃ­az', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (78, 'Diana GÃ³mez', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (79, 'Javier PÃ©rez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (80, 'Diego RodrÃ­guez', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (81, 'AndrÃ©s GÃ³mez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (82, 'Diana Vergara', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (83, 'Alejandro SÃ¡nchez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (84, 'Camila GÃ³mez', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (85, 'Gabriel RodrÃ­guez', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (86, 'Isabella PÃ©rez', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (87, 'Ana PÃ©rez', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (88, 'Diego GÃ³mez', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (89, 'Valentina Vergara', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (90, 'Fernando DÃ­az', 'Barranquilla', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (91, 'Valentina RodrÃ­guez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (92, 'MarÃ­a SÃ¡nchez', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (93, 'AndrÃ©s MartÃ­nez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (94, 'Camila DÃ­az', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (95, 'AndrÃ©s DÃ­az', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (96, 'Valentina Vergara', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (97, 'SofÃ­a DÃ­az', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (98, 'SofÃ­a Valencia', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (99, 'Valentina GÃ³mez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (100, 'Alejandro DÃ­az', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (101, 'Ana GarcÃ­a', 'BogotÃ¡', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (102, 'Carlos Vergara', 'BogotÃ¡', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (103, 'Alejandro DÃ­az', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (104, 'Isabella PÃ©rez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (105, 'Gabriel LÃ³pez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (106, 'Isabella SÃ¡nchez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (107, 'Laura PÃ©rez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (108, 'Paula SÃ¡nchez', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (109, 'Alejandro RodrÃ­guez', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (110, 'AndrÃ©s SÃ¡nchez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (111, 'Diego LÃ³pez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (112, 'Javier MartÃ­nez', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (113, 'Laura RodrÃ­guez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (114, 'MarÃ­a GarcÃ­a', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (115, 'SofÃ­a Vergara', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (116, 'Camila GÃ³mez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (117, 'SofÃ­a DÃ­az', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (118, 'Laura PÃ©rez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (119, 'Fernando LÃ³pez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (120, 'Alejandro SÃ¡nchez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (121, 'Valentina GarcÃ­a', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (122, 'Javier MartÃ­nez', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (123, 'Valentina Vergara', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (124, 'Luis GarcÃ­a', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (125, 'Carlos Vergara', 'Cali', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (126, 'Ana Vergara', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (127, 'Diana SÃ¡nchez', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (128, 'Alejandro Valencia', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (129, 'Laura SÃ¡nchez', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (130, 'SofÃ­a Vergara', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (131, 'Gabriel GarcÃ­a', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (132, 'Isabella PÃ©rez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (133, 'Isabella GÃ³mez', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (134, 'Paula RodrÃ­guez', 'Pasto', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (135, 'Alejandro GarcÃ­a', 'MedellÃ­n', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (136, 'Javier Vergara', 'Barranquilla', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (137, 'Juan Valencia', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (138, 'Ana Valencia', 'MedellÃ­n', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (139, 'Isabella GÃ³mez', 'Pasto', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (140, 'Luis PÃ©rez', 'MedellÃ­n', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (141, 'Javier RodrÃ­guez', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (142, 'Juan RodrÃ­guez', 'Barranquilla', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (143, 'AndrÃ©s GÃ³mez', 'Pasto', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (144, 'Alejandro PÃ©rez', 'Tumaco', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (145, 'AndrÃ©s SÃ¡nchez', 'Tumaco', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (146, 'Diana MartÃ­nez', 'Cali', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (147, 'Diego PÃ©rez', 'BogotÃ¡', 'Pyme') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (148, 'Luis Vergara', 'BogotÃ¡', 'Corporativo') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (149, 'Carlos RodrÃ­guez', 'Cali', 'Consumidor Final') ON CONFLICT DO NOTHING;
INSERT INTO Clientes (ClienteID, Nombre, Ciudad, Segmento) VALUES (150, 'SofÃ­a GÃ³mez', 'Tumaco', 'Corporativo') ON CONFLICT DO NOTHING;
